apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demosebr
  name: demosebr
spec:
  selector:
    matchLabels:
      app: demosebr
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: demosebr
    spec:
      containers:
        image: CONTAINER_IMAGE
        imagePullPolicy: Always
        name: demosebr
        ports:
        - containerPort: 51773
          protocol: TCP
        - containerPort: 52773
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 800Mi
          requests:
            cpu: 100m
            memory: 400Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: demosebr
spec:
  selector:
     app: demosebr
  ports:
   - protocol: TCP
     port: 52773
     targetPort: 52773
     name: webserver
   - protocol: TCP
     port: 1972
     targetPort: 1972
     name: superserver
  type: LoadBalancer
